nelmio_api_doc:
    documentation:
        info:
            title: Tuyo market
            description: This description will be provided by someone from Tuyo
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
