###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  mongo:
    image: mongo:latest
    container_name: tuyo-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: d3vRootMongoPass!@3

  mongo-express:
    image: mongo-express
    container_name: tuyo-mongo-express
    restart: always
    ports:
    - 8101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: d3vRootMongoPass!@3

  webserver:
    image: nginx:alpine
    container_name: tuyo-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./docker-tuyo/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 8100:80

  php-fpm:
    build: docker-tuyo/php-fpm
    container_name: tuyo-php
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-tuyo/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=market
      - RABBITMQ_DEFAULT_USER=market
      - RABBITMQ_DEFAULT_PASS=market

